name: Build and deploy Python app to Azure Web App - reddit-mention-tracker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and activate virtual environment
        run: |
          python -m venv backenv
          source backenv/bin/activate

      - name: Install backend dependencies
        run: |
          source backenv/bin/activate
          pip install --upgrade pip
          pip install -r backend/tracker/requirements.txt


      - name: Package backend for deployment
        run: |
          cd backend/tracker
          zip -r ../../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !backenv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip release
        run: |
          unzip release.zip -d deploy-package

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'reddit-mention-tracker'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_17E45E063F9E4B92A5D491C59D617E03 }}
          package: ./deploy-package
